apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-06-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-06-frontend
  template:
    metadata:
      labels:
        app: app-06-frontend
    spec:
      containers:
        - name: frontend
          image: app-06-frontend:latest
          ports:
            - containerPort: 4173
          livenessProbe:
            httpGet:
              path: /
              port: 4173
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 4173
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
