apiVersion: v1
kind: Secret
metadata:
  name: app-06-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:change-me@postgres:5432/app06_db
  JWT_SECRET: change-me
  JWT_REFRESH_SECRET: change-me
